# this script will parse the xml file generated by nmap and print the results.
# hot tip: don't name this parser.py as it will conflict with the built-in parser module.


import xml.etree.ElementTree as ET

def parse_nmap_xml(file_path):
    parsed_output = "" # Initialize the variable that will store the parsed output
    tree = ET.parse(file_path)
    root = tree.getroot()
    for host in root.findall('host'):
        ip = host.find('address').get('addr')
        host_info = f"Host: {ip}\n"
        for port in host.findall('.//port'):
            port_id = port.get('portid')
            state = port.find('state').get('state')
            service_element = port.find('service')
            service_name = service_element.get('name') if service_element is not None else 'Service unknown'
            host_info += f"  Port: {port_id}, State: {state}, Service: {service_name}\n"
        parsed_output += host_info + "\n"
    return parsed_output

# call this function and print its result for testing:
#print(parse_nmap_xml('output.xml'))
